# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fragaria.cz
email: info@fragaria.cz
description: ...
keywords: fragaria, software, vývoj software, webové aplikace, python, javascript, angular, elasticsearch, html, css
url: "https://fragaria.cz" # the base hostname & protocol for your site
baseurl: "/website"

sass:
    style: compressed
    sass_dir: _sass

# Build settings
markdown: kramdown

plugins:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-paginate
    - jekyll-archives


exclude:
    - Dockerfile
    - docker-compose.yml
    - readme.md
    - Gemfile
    - Gemfile.lock

permalink: /blog/:year/:month/:day/:title/

# --------------------------- plugins ------------------------------------------

paginate_path: "/blog/archive/:num/"
paginate: 11

jekyll-archives:
    enabled:
        - year
        - month
        - tags
    layout: scoped-archive
    permalinks:
        year: /blog/archive/year/:year/
        month: /blog/archive/month/:year-:month/
        tag: /blog/archive/tag/:name/

# ---------------------- custom configuration ----------------------------------

company:
    official_name: Fragaria s.r.o.
    phone: +420 222 581 311
    email: info@fragaria.cz
    ico: 48590151
    dic: CZ48590151
    listed_at: >
        Spisová značka: C 18340 vedená u Městského soudu v Praze
    address:
        residence:
            line1: Ječná 507/6
            line2: 120 00 Praha 2
        billing:
            line1: Pampelišková 2013/8
            line2: 106 00 Praha 10

