# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: fragaria.cz
email: info@fragaria.cz
description: ...
keywords: fragaria, software, vývoj software, webové aplikace, python, javascript, angular, elasticsearch, html, css
url: "https://fragaria.cz" # the base hostname & protocol for your site

sass:
    style: compressed
    sass_dir: _sass

# Build settings
markdown: kramdown

plugins:
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-paginate
    - jekyll-environment-variables

paginate_path: "/blog/:num/"
paginate: 11

exclude:
    - Dockerfile
    - docker-compose.yml
    - readme.md
    - Gemfile
    - Gemfile.lock

permalink: /blog/:title/

company:
    official_name: Fragaria s.r.o.
    phone: +420 222 581 311
    email: info@fragaria.cz
    ico: 48590151
    dic: CZ48590151
    listed_at: >
        Spisová značka: C 18340 vedená u Městského soudu v Praze
    address:
        residence:
            line1: Ječná 507/6
            line2: 120 00 Praha 2
        billing:
            line1: Pampelišková 2013/8
            line2: 106 00 Praha 10

